// tenuispack — embed a .tenb binary into a C++ source file for zero-file deployment.
// Usage: tenuispack <input.tenb> <output.cpp>
// The generated file defines TENUIS_PROGRAM[] and TENUIS_PROGRAM_SIZE.
// Compile it with src/vm/main_embedded.cpp and the VM sources to get a standalone binary.

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <cstdint>

int main(int argc, char* argv[]) {
    if (argc != 3) {
        fprintf(stderr, "usage: tenuispack <input.tenb> <output.cpp>\n");
        return 1;
    }

    // Read input .tenb file
    FILE* in = fopen(argv[1], "rb");
    if (!in) { perror(argv[1]); return 1; }
    fseek(in, 0, SEEK_END);
    const long fsz = ftell(in);
    rewind(in);
    if (fsz < 20) {
        fprintf(stderr, "tenuispack: %s: file too small to be a valid .tenb\n", argv[1]);
        fclose(in); return 1;
    }
    std::vector<uint8_t> data(static_cast<size_t>(fsz));
    if (fread(data.data(), 1, static_cast<size_t>(fsz), in) != static_cast<size_t>(fsz)) {
        fprintf(stderr, "tenuispack: read error\n"); fclose(in); return 1;
    }
    fclose(in);

    // Write generated C++ source
    FILE* out = fopen(argv[2], "w");
    if (!out) { perror(argv[2]); return 1; }

    fprintf(out, "// Auto-generated by tenuispack — do not edit.\n");
    fprintf(out, "// Source: %s\n", argv[1]);
    fprintf(out, "#include <cstdint>\n");
    fprintf(out, "extern const uint8_t  TENUIS_PROGRAM[];\n");
    fprintf(out, "extern const uint32_t TENUIS_PROGRAM_SIZE;\n");
    fprintf(out, "const uint8_t TENUIS_PROGRAM[] = {\n");

    const size_t COLS = 16;
    for (size_t i = 0; i < data.size(); ++i) {
        if (i % COLS == 0) fprintf(out, "    ");
        fprintf(out, "0x%02xu", data[i]);
        if (i + 1 < data.size()) fprintf(out, ",");
        if ((i % COLS) == COLS - 1 || i + 1 == data.size()) fprintf(out, "\n");
        else fprintf(out, " ");
    }
    fprintf(out, "};\n");
    fprintf(out, "const uint32_t TENUIS_PROGRAM_SIZE = %uu;\n",
            static_cast<unsigned>(data.size()));

    fclose(out);

    fprintf(stderr, "tenuispack: %s → %s  (%u bytes embedded)\n",
            argv[1], argv[2], static_cast<unsigned>(data.size()));
    return 0;
}
